version: '3'

services:

  elasticsearch:
    image: apm-java/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-java
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "XPACK_MONITORING_ENABLED=true"
      - "XPACK_MONITORING_COLLECTION_ENABLED=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      # Health check to validate if the elastic search is running
      test: "wget -q -O - http://elastic:changeme@localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300

  logstash:
    image: logstash:6.5.2
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USER: "$ELASTIC_USER"
      ELASTIC_PASSWORD: "$ELASTIC_PASSWORD"
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: "$ELASTIC_USER"
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: "$ELASTIC_PASSWORD"
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
      - "XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true"
      - "XPACK_MONITORING_COLLECTION_ENABLED=true"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
