# This file has the prometheus datasource details that grafana uses to get metrics from.

datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'http://prometheus:9090'
    is_default: true
    version: 1
    editable: true